# kubernetes/patient-service/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-service-config
  namespace: hospital-system
data:
  APP_NAME: "patient-service"
  APP_VERSION: "1.0.0"
  APP_PORT: "3001"
  APP_ENV: "production"
  DB_HOST: "sqlserver-service"
  DB_PORT: "1433"
  DB_NAME: "hospital_patient_db"
  JWT_EXPIRE_HOURS: "24"