# kubernetes/sqlserver/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: hospital-system
spec:
  type: ClusterIP
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqlserver