# docker-compose.yml
version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: hospital_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - hospital_network

  patient-service:
    build:
      context: ./services/patient-service
      dockerfile: Dockerfile
    container_name: patient_service
    ports:
      - "3001:3001"
    environment:
      - APP_ENV=development
      - APP_PORT=3001
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Passw0rd
      - DB_NAME=hospital_patient_db
      - JWT_SECRET=your-secret-key-change-this-in-production
    depends_on:
      - sqlserver
    networks:
      - hospital_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - hospital_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - hospital_network

volumes:
  sqlserver_data:
  prometheus_data:
  grafana_data:

networks:
  hospital_network:
    driver: bridge